export const  ActionTypes = {
   SET_POKEMONS: 'SET_POKEMONS',
   SET_POKEMON_SELECTED: 'SET_POKEMON_SELECTED',
   SET_TEAM: 'SET_TEAM',
   ADD_TO_TEAM: 'ADD_TO_TEAM',
   REMOVE_FROM_TEAM: 'REMOVE_FROM_TEAM',
   DELETE_TEAM: 'DELETE_TEAM',
};