export const  ActionTypes = {
   SET_POKEMONS: 'SET_POKEMONS',
   SET_POKEMON_SELECTED: 'SET_POKEMON_SELECTED',
   SET_SELECTED_TEAM: 'SET_SELECTED_TEAM',
   SET_TEAM_NAME: 'SET_TEAM_NAME',
   ADD_TO_TEAM: 'ADD_TO_TEAM',
   REMOVE_FROM_TEAM: 'REMOVE_FROM_TEAM',
   DELETE_TEAM: 'DELETE_TEAM',
   SAVE_TEAM: 'SAVE_TEAM',
   SET_PREVIOUS_TEAM_NAME: 'SET_PREVIOUS_TEAM_NAME',
};